In [1]:
# import libs
import numpy as np
import pandas as pd
import os

In [2]:
def getcols(filename):
    data = pd.read_csv(filename, nrows = 2)
    return data.columns

In [3]:
# 从文件夹'newdata/'中读取数据文件
filedir = '/mnt/hgfs/vmfiles/newdata/'
files = os.listdir(filedir)

In [4]:
files

['BENIGN_data.csv',
 'DrDoS_DNS_data.csv',
 'DrDoS_LDAP_data.csv',
 'DrDoS_MSSQL_data.csv',
 'DrDoS_NetBIOS_data.csv',
 'DrDoS_NTP_data.csv',
 'DrDoS_SNMP_data.csv',
 'DrDoS_SSDP_data.csv',
 'DrDoS_UDP_data.csv',
 'Syn_data.csv',
 'TFTP_data.csv']

In [32]:
l = range(1000000)
d = pd.read_csv(filedir+files[1],skiprows=lambda x: (x % 100000) > 10,nrows = 50)

In [34]:
101709 % 100000

1709

In [37]:
d = d[0:20000]
d

,Unnamed: 0,Unnamed: 0.1,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,425,172.16.0.5-192.168.50.1-634-60495-17,172.16.0.5,634,192.168.50.1,60495,17,2018-12-01 10:51:39.813448,28415,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
1,1,430,172.16.0.5-192.168.50.1-60495-634-17,192.168.50.1,634,172.16.0.5,60495,17,2018-12-01 10:51:39.820842,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,DrDoS_DNS
2,2,1654,172.16.0.5-192.168.50.1-634-46391-17,172.16.0.5,634,192.168.50.1,46391,17,2018-12-01 10:51:39.852499,48549,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
3,3,2927,172.16.0.5-192.168.50.1-634-11894-17,172.16.0.5,634,192.168.50.1,11894,17,2018-12-01 10:51:39.890213,48337,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
4,4,694,172.16.0.5-192.168.50.1-634-27878-17,172.16.0.5,634,192.168.50.1,27878,17,2018-12-01 10:51:39.941151,32026,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
5,5,838,172.16.0.5-192.168.50.1-634-47149-17,172.16.0.5,634,192.168.50.1,47149,17,2018-12-01 10:51:39.942030,46469,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
6,6,3090,172.16.0.5-192.168.50.1-634-22713-17,172.16.0.5,634,192.168.50.1,22713,17,2018-12-01 10:51:39.973650,31201,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
7,7,2594,172.16.0.5-192.168.50.1-634-49912-17,172.16.0.5,634,192.168.50.1,49912,17,2018-12-01 10:51:39.994394,50453,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
8,8,2698,172.16.0.5-192.168.50.1-634-56681-17,172.16.0.5,634,192.168.50.1,56681,17,2018-12-01 10:51:40.005191,31008,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
9,9,277,172.16.0.5-192.168.50.1-634-13161-17,172.16.0.5,634,192.168.50.1,13161,17,2018-12-01 10:51:40.036581,30143,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
10,101709,3394,172.16.0.5-192.168.50.1-873-38906-17,172.16.0.5,873,192.168.50.1,38906,17,2018-12-01 11:06:14.708776,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
11,101710,21427,172.16.0.5-192.168.50.1-874-19308-17,172.16.0.5,874,192.168.50.1,19308,17,2018-12-01 11:06:14.708905,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
12,101711,9865,172.16.0.5-192.168.50.1-875-8811-17,172.16.0.5,875,192.168.50.1,8811,17,2018-12-01 11:06:14.708958,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
13,101712,495,172.16.0.5-192.168.50.1-876-49972-17,172.16.0.5,876,192.168.50.1,49972,17,2018-12-01 11:06:14.709194,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
14,101713,14543,172.16.0.5-192.168.50.1-877-26356-17,172.16.0.5,877,192.168.50.1,26356,17,2018-12-01 11:06:14.709221,71,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
15,101714,20335,172.16.0.5-192.168.50.1-878-29520-17,172.16.0.5,878,192.168.50.1,29520,17,2018-12-01 11:06:14.709296,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
16,101715,5323,172.16.0.5-192.168.50.1-879-28904-17,172.16.0.5,879,192.168.50.1,28904,17,2018-12-01 11:06:14.709351,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
17,101716,15172,172.16.0.5-192.168.50.1-880-7759-17,172.16.0.5,880,192.168.50.1,7759,17,2018-12-01 11:06:14.709399,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
18,101717,23662,172.16.0.5-192.168.50.1-881-32408-17,172.16.0.5,881,192.168.50.1,32408,17,2018-12-01 11:06:14.709505,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
19,101718,22444,172.16.0.5-192.168.50.1-564-15715-17,172.16.0.5,564,192.168.50.1,15715,17,2018-12-01 11:06:14.709556,50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS

In [58]:
a = d[[' Packet Length Mean',' Active Max']]
b = a.mean()
c = a/ b

In [59]:
a

     Packet Length Mean   Active Max
0                 440.0          0.0
1                 440.0          0.0
2                 440.0          0.0
3                 440.0          0.0
4                 440.0          0.0
5                 440.0          0.0
6                 440.0          0.0
7                 440.0          0.0
8                 440.0          0.0
9                 440.0          0.0
10                362.0          0.0
11               1472.0          0.0
12               1448.0          0.0
13               1472.0          0.0
14               1472.0          0.0
15               1472.0          0.0
16               1472.0          0.0
17                823.0          0.0
18               1472.0          0.0
19               1472.0          0.0

In [60]:
a.astype('int64',copy=False)

     Packet Length Mean   Active Max
0                   440            0
1                   440            0
2                   440            0
3                   440            0
4                   440            0
5                   440            0
6                   440            0
7                   440            0
8                   440            0
9                   440            0
10                  362            0
11                 1472            0
12                 1448            0
13                 1472            0
14                 1472            0
15                 1472            0
16                 1472            0
17                  823            0
18                 1472            0
19                 1472            0

In [61]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0    Packet Length Mean  20 non-null     float64
 1    Active Max          20 non-null     float64
dtypes: float64(2)
memory usage: 448.0 bytes

In [57]:
c

     Packet Length Mean   Active Max
0              0.507585          NaN
1              0.507585          NaN
2              0.507585          NaN
3              0.507585          NaN
4              0.507585          NaN
5              0.507585          NaN
6              0.507585          NaN
7              0.507585          NaN
8              0.507585          NaN
9              0.507585          NaN
10             0.417604          NaN
11             1.698102          NaN
12             1.670416          NaN
13             1.698102          NaN
14             1.698102          NaN
15             1.698102          NaN
16             1.698102          NaN
17             0.949415          NaN
18             1.698102          NaN
19             1.698102          NaN

In [55]:
a = [1,2,3,4,5]
b = np.array(a).mean()

In [56]:
b

3.0

In [57]:
4 // 2

2

In [58]:
3 //2

1

In [59]:
5 //3

1